### ISSUE TITLE
help to make this work

### ISSUE THREAD

**Issue by xoceunder** [kaltura/nginx-secure-token-module#20]
I help to make this work do not see an example
@gonen

**Comment by erankor** [comment]
can you explain the use case you wish to support ? this question is quite vague...

**Comment by xoceunder** [comment]
I want to protect my streaming so that if I capture is protected
ch1.m3u8?st=PG4LipwVIkqCKLmpjKFTHQ&e=1430348566

**Comment by erankor** [comment]
Ok, and are you using a CDN or streaming directly from nginx ? if CDN, which one ?

**Comment by xoceunder** [comment]
I am using this

Nginx-RTMP + ffmpeg

**Comment by xoceunder** [comment]
streaming directly from nginx

**Comment by xoceunder** [comment]
and I have to work but now the problem is I do not play

http://162.243.42.4:8080/hls/test/index.m3u8?token=4IH6Ycedmlxpb45PivDgEw&expire=1437523198

**Comment by xoceunder** [comment]
http://prntscr.com/7vg68j

**Comment by erankor** [comment]
Ok, so to make this setup work, there are 2 things the nginx server has to do:
1. Make sure the requests for hls manifests / segments have a valid token, and fail the request otherwise
2. Propagate the token from the manifest request to the URLs contained inside it. In other words, in HLS, for example, you have an M3U8 playlist that contains links to the MPEG-TS video files, these URLs must contain valid tokens, otherwise they won't work, due to requirement 1.

This module can help you solve requirement 2, it can manipulate the manifest response and add tokens where needed. However, as I understand, you are using nginx's secure link tokens, and these are currently not supported by this module, this module supports Akamai V2 tokens and Amazon CloudFront tokens. So, to be able to use this module, you will have to change the token format to Akamai's.
In order to implement requirement 1 with Akamai tokens, you can use a different module - https://github.com/kaltura/nginx-akamai-token-validate-module.

Here is a sample configuration that adds token security on top of some remote live stream generated by a Wowza streaming server:
                location /kLive/ {

                                proxy_pass http://original-live-domain;

                                secure_token akamai;
                                secure_token_akamai_key 1234;
                                secure_token_akamai_acl "$baseuri*";
                                secure_token_types text/xml application/vnd.apple.mpegurl;
                                secure_token_content_type_f4m text/xml;

                                akamai_token_validate on;
                                akamai_token_validate_key 1234;
                                akamai_token_validate_strip_token on;
                }
In your setup you don't need to use proxy-pass, just add all the other switches (except strip_token=on) on the nginx location for /hls. 

Btw, this module identifies the manifest responses that should be processed according to their mime type, you may need to update this setting if the defaults do not work for you. When we tested with Wowza, for example, we saw that it does not send the standard video/f4m mime type for HDS manifest, but rather sends text/xml, that is the reason the sample above changes the default.

**Comment by xoceunder** [comment]
and as would be the token to this module

**Comment by erankor** [comment]
Didn't understand, was that a question ?

**Comment by xoceunder** [comment]
as is the structure of this module to create token will link

**Comment by jessp01** [comment]
Hello,

Sorry but I'm afraid we still don't understand the question. Can you please reiterate?
