### ISSUE TITLE
Dynamic IV

### ISSUE THREAD

**Issue by ludal13** [kaltura/nginx-secure-token-module#47]
Hi,

I'm searching a way to handle dynamic IV with your module.
But, according to nginx error.log (secure_token_encrypt_uri_key" directive invalid hex string), and reading the sources, I understood that it's not possible actually.
Am I right ?

Do you plan to add this feature ?

Here is a configuration example:

```
        location ~ "^/(?<iv>([^/]+))/(?<key>([^/]+))" {
                secure_token_encrypt_uri        on;
                secure_token_encrypt_uri_key    000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f;
                secure_token_encrypt_uri_iv     $iv;
                secure_token_encrypt_uri_part   $key;
        }
```

Thanks.

**Comment by erankor** [comment]
That is correct, it's not supported.
But I'm not sure what you meant by dynamic, if you meant that it will support nginx variables, then the feature makes sense, but we don't support it.
If you meant that the values will change over time then that is problematic, since -
1. The URL is generated by some other system, which means changes will need to be synched between these 2 systems
2. Frequent changes in key/iv will make caching of these requests (via CDN/proxy) less efficient.

**Comment by ludal13** [comment]
Hello,

OK, got it. Do you plan to support this feature ?

By dynamic, I meant this : I would like to change the IV everytime time I do generate a crypted URI.
Since the IV is always placed at the same position, it's easy to capture it in a nginx variable for uncrypting.

I do agree with you about the CDN / proxy / caching part. But, once again, since we do were the IV part is, it's also easy to exclude it from the cachekey.

**Comment by erankor** [comment]
Sorry, no plans to add this feature at the moment
