### ISSUE TITLE
Logging decoded url

### ISSUE THREAD

**Issue by peacemhy** [kaltura/nginx-secure-token-module#54]
Hi all, 
I was wondering about logging the decoded url, is there any way to get the decoded url part as a global variable to use in log format.

Any help is appreciated.

**Comment by erankor** [comment]
The question is about url encryption? if so, you can probably just log `$uri`, the module updates the request uri with the decrypted url. Usually `$request` is used in the access log format and not `$uri` (in log format=combined, for example), so that is probably the reason you see the encrypted uri.

**Comment by peacemhy** [comment]
That is was i was looking for `$uri`  :thumbsup:
Thanks a bunch
