### ISSUE TITLE
Incorrect appending of token with EXT-X-KEY and base64 data

### ISSUE THREAD

**Issue by cstranex** [kaltura/nginx-secure-token-module#94]
Given a manifest that has these entries:
```
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://expressplay_token",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,AAAARnBzc2gBAAAA7e+LqXnWSs6jyCfc1R0h7QAAAAFhYWFhYWFhYWFhYWFhYWFhAAAAEhIQYWFhYWFhYWFhYWFhYWFhYQ==",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYID=0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,KEYFORMATVERSIONS="1"
```

The second EXT-X-KEY line ends with an equals which causes nginx-secure-token-module to append the token to the end of it creating invalid data.

Looking at the code the state machine seems to look for an `=` followed by a `"` to decide when to inject the token. Perhaps it can rather determine whether URI begins with "data:"?

**Comment by erankor** [comment]
It makes sense, but I'm wondering, you already have DRM... why bother with tokens?

**Comment by cstranex** [comment]
We have a mixture of DRM-ed and non-DRMed content so while it is not specifically needed it just makes configuration easier :smile:

**Comment by cstranex** [comment]
Actually having a look a bit more, the token injection does try validate the scheme but it assumes the scheme is delimited by a ["://"](https://github.com/kaltura/nginx-secure-token-module/blob/95bdc0d1aca06ea7fe42555f71e65910bd74914d/ngx_http_secure_token_processor_base.c#L119)

I think changing `scheme_delimeter` to ":" instead of "://" will solve the issue. I can open a pull request if you like

**Comment by erankor** [comment]
Yes, it will solve this one, but it will probably create other problems... the state machine will move to STATE_URL_PATH too early when the URI contains `://`. 
Maybe a better solution is to add a boolean for `is_http_scheme` (instead of the function) - set it to true by default, and if `:` is encountered, check if it's http/https and update it accordingly.

**Comment by erankor** [comment]
Had a second thought here (sorry...) - when the scheme is not http/https (and probably only real world examples of this are `skd://` & `data:`) parsing the rest of the URI is pointless. 
So, instead of my previous suggestion of adding a boolean, I think it would be better to add another state - STATE_URL_NON_HTTP. This state won't have a case in the switch, it will just wait until the end marker is received. 
The check on `is_http_scheme` will be replaced with state != STATE_URL_NON_HTTP.

Two other comments about your implementation -
1. The indent in this module is using tabs
2. I would prefer to be more strict about the scheme - allow only http & https, and not http* (as it is now)

**Comment by cstranex** [comment]
Okay, I have updated the PR to keep a slightly modified `ngx_http_secure_token_is_http_scheme` that will check if the scheme is http or https. If not it will switch to the STATE_URL_NON_HTTP state.

**Comment by erankor** [comment]
Thanks! merged
